version: '3.8'

services:
  fastapi:
    build:
        context: .
        dockerfile: Dockerfile
    networks:
      - mynetwork
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    container_name: fastapi
    ports:
      - "8000:80"
    depends_on:
      - kafka
      - redis
    environment:
      - MODULE_NAME=main  # Set this to the name of the Python file (without the .py extension) that contains your FastAPI application
      - VARIABLE_NAME=app  # Set this to the name of the FastAPI application instance in that file
      - DATABASE_URL=mysql://root:root_password@mysql:3306/twitter
      - DATABASE_TABLE=twitter
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root_password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    volumes:
      - .:/app


  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"

networks:
  mynetwork:
    external: true
