version: '3.8'

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    container_name: fastapi
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - kafka
      - redis
    environment:
      - DATABASE_URL=mysql://root:password@mysql:6306/mydatabase
      - DATABASE_TABLE=mytable
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    container_name: mysql-python
    ports:
      - "6306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
